config/routes.rb
Rails.application.routes.draw do
  root "polls#index"
  resources :polls
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: %i[show edit update destroy]
  # 略
  def index
    @polls = Poll.order(id: :asc)
  end

  def show

  end

  def edit

  end

  def update
    @poll.update!(poll_params)
    redirect_to poll, notice: "更新しました"
  end

  def new
  # ***** 以下を追加 *****
    @poll = Poll.new
  # ***** 以上を追加 *****
  end

  def create
  # ***** 以下を追加 *****
    poll = Poll.create!(poll_params)
    redirect_to poll, notice: "投稿しました"
  # ***** 以上を追加 *****
  end

  def destroy
    @poll.destroy!
    redirect_to root_path, alert: "削除しました"
  end

  def set_poll
    @poll = Poll.find(params[:id])

  # ***** 以下を追加 *****
  private

  def poll_params
    params.require(:poll).permit(:title, :content)
  end
  # ***** 以上を追加 *****
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <p style="color: <%= flash_type == 'notice' ? 'green' : 'red' %>;"><%= msg %></p>
  <hr>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "投稿一覧", polls_path %> <%= link_to "新規投稿", new_poll_path %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/polls/_form.html.erb
<%= form_with model: @poll, local: true do |form| %>
  <div>
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, "内容" %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.submit buttom_value %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/polls/index.html.erb
<h1>投稿一覧</h1>
<table>
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">タイトル</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each.with_index(1) do |poll, i| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td><%= poll.title %></td>
        <td>
          <%= link_to "詳細", poll %>
          <%= link_to "編集", edit_poll_path(poll) %>
          <%= link_to "削除", poll, method: :delete, data: { confirm: "削除しますか?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/polls/new.html.erb
<h1>新規投稿</h1>
<%= render "form", button_value "投稿" %>

app/views/polls/show.html.erb
<h1>投稿詳細</h1>
<p>タイトル <%= @poll.title %></p>
<p>内容 <%= @poll.content %></p>